apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  namespace: bookapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
      - name: book-service
        image: bossdan/book-service:1.0
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: booksdb
        - name: DB_USER
          value: postgres
        - name: DB_PASS
          value: postgres
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: bookapp
spec:
  type: LoadBalancer  # or NodePort if no cloud LB
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: book-service
